/**
 * 覆盖层 UI 模板（HTML 与 CSS）
 * 方向 C：悬浮球模式 —— 右下角悬浮球 + 按需弹出小面板
 */
const { t } = require("../i18n/i18n");
// Фон страницы теперь применяется динамически из настроек (см. background.js),
// через внутренний протокол cuckoo-asset:// — CSS-правило пустое, скрывает
// только базовый цвет под картинкой.

function buildOverlayHTML() {
  return [
    '<div id="cuckoo-overlay" class="cuckoo-overlay cuckoo-hidden">',
    '  <div class="cuckoo-header" id="cuckoo-overlay-drag">',
    '    <span class="cuckoo-title">Cookie Code</span>',
    '    <button id="cuckoo-btn-minimize" class="cuckoo-btn-icon" title="' +
      t("overlay.btn.minimize") +
      '">×</button>',
    "  </div>",
    '  <div class="cuckoo-body">',
    '    <div class="cuckoo-section cuckoo-project-dir-section">',
    '      <div class="cuckoo-project-dir-row">',
    '        <span class="cuckoo-label">' +
      t("overlay.label.currentDir") +
      "</span>",
    '        <button id="cuckoo-btn-change-dir" class="cuckoo-btn-change-dir" title="' +
      t("overlay.btn.changeDir.title") +
      '">' +
      t("overlay.btn.changeDir") +
      "</button>",
    "      </div>",
    '      <div id="cuckoo-project-dir-display" class="cuckoo-project-dir-display">',
    '        <span class="cuckoo-dir-path">' +
      t("overlay.dir.notSelected") +
      "</span>",
    "      </div>",
    "    </div>",
    '    <div class="cuckoo-divider"></div>',
    '    <div class="cuckoo-section cuckoo-token-section">',
    '      <label class="cuckoo-label">' +
      t("overlay.label.convTokens") +
      "</label>",
    '      <div class="cuckoo-token-display">',
    '        <span id="cuckoo-conv-token-count" class="cuckoo-token-count">0</span>',
    '        <span class="cuckoo-token-unit">tokens</span>',
    "      </div>",
    "    </div>",
    '    <div class="cuckoo-divider"></div>',
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-btn-init" class="cuckoo-btn cuckoo-btn-primary">' +
      t("overlay.btn.init") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-btn-window-manager" class="cuckoo-btn cuckoo-btn-secondary" title="' +
      t("overlay.btn.windowManager.title") +
      '">' +
      t("overlay.btn.windowManager") +
      "</button>",
    '      <button id="cuckoo-btn-mcp" class="cuckoo-btn cuckoo-btn-secondary" title="' +
      t("overlay.btn.mcp.title") +
      '">MCP</button>',
    '      <button id="cuckoo-btn-diff" class="cuckoo-btn cuckoo-btn-secondary" title="' +
      t("diff.btn.title") +
      '">Diff</button>',
    "    </div>",
    '    <div class="cuckoo-actions">',
    '<button id="cuckoo-btn-gen-doc" class="cuckoo-btn cuckoo-btn-primary" title="' +
      t("overlay.btn.genDoc.title") +
      '">' +
      t("overlay.btn.genDoc") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-btn-immersive" class="cuckoo-btn cuckoo-btn-secondary" title="' +
      t("overlay.btn.immersive.title") +
      '">' +
      t("overlay.btn.immersive") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-btn-manual-parse" class="cuckoo-btn cuckoo-btn-secondary" title="' +
      t("overlay.btn.manualParse.title") +
      '">' +
      t("overlay.btn.manualParse") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-btn-context-port" class="cuckoo-btn cuckoo-btn-secondary" title="' +
      t("overlay.btn.contextPort.title") +
      '">' +
      t("overlay.btn.contextPort") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-divider"></div>',
    '    <div class="cuckoo-section cuckoo-session-section">',
    '      <div class="cuckoo-session-header">',
    '        <span class="cuckoo-label">' +
      t("overlay.label.sessions") +
      "</span>",
    '        <button id="cuckoo-btn-refresh-sessions" class="cuckoo-btn-refresh-sessions" title="' +
      t("overlay.btn.refreshSessions") +
      '">' +
      t("overlay.btn.refreshSessions") +
      "</button>",
    "      </div>",
    '      <div id="cuckoo-session-list" class="cuckoo-session-list">',
    '        <div class="cuckoo-session-empty">' +
      t("overlay.sessions.empty") +
      "</div>",
    "      </div>",
    "    </div>",
    '    <div class="cuckoo-divider"></div>',
    '    <div class="cuckoo-section">',
    '      <label class="cuckoo-label">' +
      t("overlay.label.sendDelay") +
      "</label>",
    '      <div class="cuckoo-blur-row">',
    '        <div class="cuckoo-delay-label">',
    '          <input id="cuckoo-delay-min" class="cuckoo-input" type="number" min="0" step="0.1" value="2" />',
    '          <span class="cuckoo-blur-value">' +
      t("overlay.label.delayRange") +
      "</span>",
    '          <input id="cuckoo-delay-max" class="cuckoo-input" type="number" min="0" step="0.1" value="4" />',
    '          <span class="cuckoo-blur-value">' +
      t("overlay.label.delaySeconds") +
      "</span>",
    "        </div>",
    "      </div>",
    '      <button id="cuckoo-btn-save-delay" class="cuckoo-btn-text" style="align-self:flex-end;">' +
      t("overlay.btn.saveDelay") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-divider"></div>',
    '    <div class="cuckoo-section">',
    '      <label class="cuckoo-label">' +
      t("overlay.label.task") +
      '<span id="cuckoo-task-status" class="cuckoo-task-status cuckoo-hidden"><span class="cuckoo-spinner"></span>' +
      t("overlay.task.running") +
      '<button id="cuckoo-btn-kill" class="cuckoo-btn-kill" title="' +
      t("overlay.task.kill.title") +
      '">' +
      t("overlay.task.kill") +
      "</button></span></label>",
    '      <pre id="cuckoo-cmd-preview" class="cuckoo-cmd-preview">' +
      t("overlay.cmd.none") +
      "</pre>",
    "    </div>",
    '    <div id="cuckoo-result-section" class="cuckoo-section cuckoo-hidden">',
    '      <label class="cuckoo-label">' +
      t("overlay.label.result") +
      "</label>",
    '      <div id="cuckoo-result-status" class="cuckoo-result-status"></div>',
    '      <pre id="cuckoo-result-output" class="cuckoo-result-output"></pre>',
    "    </div>",
    '    <div class="cuckoo-section">',
    '      <details id="cuckoo-history">',
    '        <summary class="cuckoo-label">' +
      t("overlay.label.history") +
      "</summary>",
    '        <div id="cuckoo-history-list" class="cuckoo-history-list"></div>',
    '        <button id="cuckoo-btn-clear" class="cuckoo-btn-text">' +
      t("overlay.btn.clearHistory") +
      "</button>",
    "      </details>",
    "    </div>",
    "  </div>",
    "</div>",
    '<div id="cuckoo-window-manager" class="cuckoo-window-manager cuckoo-hidden">',
    '  <div class="cuckoo-wm-header">',
    '    <span class="cuckoo-title">' + t("wm.title") + "</span>",
    '    <button id="cuckoo-wm-close" class="cuckoo-btn-icon" title="' +
      t("wm.btn.close") +
      '">×</button>',
    "  </div>",
    '  <div class="cuckoo-wm-body">',
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-wm-new-window" class="cuckoo-btn cuckoo-btn-primary">' +
      t("wm.btn.newWindow") +
      "</button>",
    "    </div>",
    '    <div class="cuckoo-divider"></div>',
    '    <div class="cuckoo-section">',
    '      <div class="cuckoo-session-header">',
    '        <span class="cuckoo-label">' + t("wm.label.list") + "</span>",
    '        <button id="cuckoo-wm-refresh" class="cuckoo-btn-refresh-sessions" title="' +
      t("wm.btn.refresh") +
      '">' +
      t("wm.btn.refresh") +
      "</button>",
    "      </div>",
    '      <div id="cuckoo-window-list" class="cuckoo-session-list">',
    '        <div class="cuckoo-session-empty">' + t("wm.empty") + "</div>",
    "      </div>",
    "    </div>",
    "  </div>",
    "</div>",
    '<div id="cuckoo-mcp-manager" class="cuckoo-window-manager cuckoo-hidden">',
    '  <div class="cuckoo-wm-header">',
    '    <span class="cuckoo-title">' + t("mcp.title") + "</span>",
    '    <button id="cuckoo-mcp-close" class="cuckoo-btn-icon" title="' +
      t("wm.btn.close") +
      '">×</button>',
    "  </div>",
    '  <div class="cuckoo-wm-body cuckoo-mcp-body">',
    '    <div class="cuckoo-mcp-left">',
    '      <div class="cuckoo-session-header">',
    '        <span class="cuckoo-label">' +
      t("mcp.label.configured") +
      "</span>",
    '        <button id="cuckoo-mcp-refresh" class="cuckoo-btn-refresh-sessions" title="' +
      t("wm.btn.refresh") +
      '">🔄</button>',
    "      </div>",
    '      <div id="cuckoo-mcp-list" class="cuckoo-session-list">',
    '        <div class="cuckoo-session-empty">' + t("mcp.empty") + "</div>",
    "      </div>",
    "    </div>",
    '    <div class="cuckoo-mcp-right">',
    '      <textarea id="cuckoo-mcp-json" class="cuckoo-cmd-preview cuckoo-mcp-json" rows="14" style="font-size:11px;" placeholder="{\n  \"mcpServers\": {\n    \"filesystem\": {\n      \"command\": \"npx\",\n      \"args\": [\"-y\", \"@modelcontextprotocol/server-filesystem\", \"C:/my-project\"]\n    }\n  }\n}"></textarea>',
    '      <div class="cuckoo-actions">',
    '        <button id="cuckoo-mcp-save" type="button" class="cuckoo-btn cuckoo-btn-primary">' +
      t("mcp.btn.save") +
      "</button>",
    "      </div>",
    "    </div>",
    "  </div>",
    "</div>",
    '<div id="cuckoo-diff-panel" class="cuckoo-window-manager cuckoo-hidden">',
    '  <div class="cuckoo-wm-header">',
    '    <span class="cuckoo-title">' + t("diff.title") + "</span>",
    '    <div style="display:flex;gap:6px;align-items:center;">',
    '      <button id="cuckoo-diff-refresh" class="cuckoo-btn-refresh-sessions" title="' +
      t("diff.btn.refresh") +
      '">🔄</button>',
    '      <button id="cuckoo-diff-close" class="cuckoo-btn-icon" title="' +
      t("diff.btn.close") +
      '">×</button>',
    "    </div>",
    "  </div>",
    '  <div class="cuckoo-diff-tabs">',
    '    <button id="cuckoo-diff-tab-changes" class="cuckoo-diff-tab active">' +
      t("diff.tab.changes") +
      "</button>",
    '    <button id="cuckoo-diff-tab-history" class="cuckoo-diff-tab">' +
      t("diff.tab.history") +
      "</button>",
    "  </div>",
    '  <div class="cuckoo-wm-body cuckoo-diff-body">',
    '    <div id="cuckoo-diff-list" class="cuckoo-diff-list">',
    '      <div class="cuckoo-session-empty">' + t("diff.loading") + "</div>",
    "    </div>",
    '    <div id="cuckoo-git-log-list" class="cuckoo-diff-list cuckoo-hidden"></div>',
    '    <div id="cuckoo-commit-files" class="cuckoo-commit-files cuckoo-hidden">',
    '      <div class="cuckoo-commit-files-header">',
    '        <button id="cuckoo-commit-back" class="cuckoo-btn-text" title="' +
      t("diff.commit.back.title") +
      '">' +
      t("diff.commit.back") +
      "</button>",
    '        <span id="cuckoo-commit-subject" class="cuckoo-commit-subject"></span>',
    '        <button id="cuckoo-commit-full" class="cuckoo-btn-refresh-sessions" title="' +
      t("diff.commit.full.title") +
      '">' +
      t("diff.commit.full") +
      "</button>",
    "      </div>",
    '      <div id="cuckoo-commit-files-list" class="cuckoo-diff-list"></div>',
    "    </div>",
    "  </div>",
    "</div>",
    '<div id="cuckoo-diff-viewer" class="cuckoo-diff-viewer cuckoo-hidden">',
    '  <div class="cuckoo-wm-header">',
    '    <span id="cuckoo-diff-viewer-title" class="cuckoo-title">diff</span>',
    '    <button id="cuckoo-diff-viewer-close" class="cuckoo-btn-icon" title="' +
      t("diff.btn.close") +
      '">×</button>',
    "  </div>",
    '  <div id="cuckoo-diff-viewer-body" class="cuckoo-diff-viewer-body"></div>',
    "</div>",
    '<div id="cuckoo-todo-panel" class="cuckoo-todo-panel cuckoo-hidden">',
    '  <div class="cuckoo-todo-header" id="cuckoo-todo-drag">',
    '    <span class="cuckoo-todo-title">Cookie Code</span>',
    '    <div class="cuckoo-todo-header-right">',
    '      <span id="cuckoo-todo-counter" class="cuckoo-todo-counter">0/0</span>',
    '      <button id="cuckoo-todo-close" class="cuckoo-btn-icon" title="' +
      t("todo.btn.hide") +
      '">×</button>',
    "    </div>",
    "  </div>",
    '  <div class="cuckoo-todo-body">',
    '    <div id="cuckoo-todo-list" class="cuckoo-todo-list"></div>',
    "  </div>",
    "</div>",
    '<button id="cuckoo-todo-tab" class="cuckoo-todo-tab cuckoo-hidden" title="' +
      t("todo.btn.show") +
      '">',
    "  <span>Todo</span>",
    '  <span id="cuckoo-todo-tab-counter" class="cuckoo-todo-tab-counter">0/0</span>',
    "</button>",
    '<div id="cuckoo-status-badge" title="' + t("badge.title") + '">',
    '  <span id="cuckoo-status-dot"></span>',
    '  <span class="cuckoo-fab-icon"></span>',
    "</div>",
    '<div id="cuckoo-first-time-dialog" class="cuckoo-first-time-dialog cuckoo-hidden">',
    '  <div class="cuckoo-first-time-box">',
    '    <button id="cuckoo-btn-first-close" class="cuckoo-btn-icon cuckoo-first-time-close" title="' +
      t("wm.btn.close") +
      '">×</button>',
    '    <div class="cuckoo-first-time-text">' + t("firstTime.text") + "</div>",
    '    <div class="cuckoo-actions">',
    '      <button id="cuckoo-btn-first-init" class="cuckoo-btn cuckoo-btn-primary">' +
      t("overlay.btn.init") +
      "</button>",
    "    </div>",
    "  </div>",
    "</div>",
  ].join("\n");
}

const OVERLAY_CSS = [
  ":root {",
  "  --ck-bg: rgba(17, 19, 34, 0.97);",
  "  --ck-surface: rgba(255, 255, 255, 0.04);",
  "  --ck-surface-hover: rgba(255, 255, 255, 0.08);",
  "  --ck-border: rgba(255, 255, 255, 0.08);",
  "  --ck-primary: #8b93ff;",
  "  --ck-primary-strong: #6d76ff;",
  "  --ck-text: #dde1ff;",
  "  --ck-text-dim: #8a90b8;",
  "  --ck-green: #4ade80;",
  "  --ck-red: #ff6b7a;",
  "  --ck-code-bg: rgba(0, 0, 0, 0.35);",
  "}",
  ".cuckoo-overlay {",
  "  position: fixed; bottom: 84px; right: 24px; width: var(--cuckoo-overlay-width, 300px); max-height: 60vh;",
  "  background: var(--cuckoo-overlay-bg, rgba(17, 19, 34, 0.72));",
  "  backdrop-filter: blur(var(--cuckoo-overlay-blur, 12px)) saturate(140%);",
  "  -webkit-backdrop-filter: blur(var(--cuckoo-overlay-blur, 12px)) saturate(140%);",
  "  border: 1px solid var(--ck-border);",
  "  border-radius: 16px;",
  "  z-index: 2147483647;",
  "  will-change: transform;",
  "  display: flex; flex-direction: column;",
  "  box-shadow: 0 12px 40px rgba(0, 0, 0, 0.45), 0 0 0 1px rgba(139, 147, 255, 0.06);",
  "  transition: opacity 0.22s ease, transform 0.22s ease;",
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
  "  color: var(--ck-text); font-size: 13px; line-height: 1.55;",
  "  overflow: hidden;",
  "}",
  ".cuckoo-overlay.cuckoo-hidden { opacity: 0; pointer-events: none; transform: translateY(8px); }",
  ".cuckoo-header {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  padding: 12px 16px 10px; flex-shrink: 0; cursor: grab; user-select: none;",
  "  border-bottom: 1px solid var(--ck-border);",
  "  background: rgba(255, 255, 255, 0.04);",
  "  backdrop-filter: blur(8px);",
  "  -webkit-backdrop-filter: blur(8px);",
  "}",
  ".cuckoo-header:active { cursor: grabbing; }",
  ".cuckoo-title { font-size: 14px; font-weight: 700; color: #c8ccff; letter-spacing: 0.4px; }",
  ".cuckoo-btn-icon {",
  "  background: var(--ck-surface); border: 1px solid var(--ck-border); color: #8a90b8;",
  "  cursor: pointer; font-size: 16px; width: 28px; height: 28px; border-radius: 8px;",
  "  display: flex; align-items: center; justify-content: center; transition: all 0.2s;",
  "  line-height: 1;",
  "}",
  ".cuckoo-btn-icon:hover { background: var(--ck-surface-hover); color: #fff; }",
  ".cuckoo-body { padding: 12px 14px; overflow-y: auto; flex: 1; display: flex; flex-direction: column; gap: 12px; }",
  ".cuckoo-section { display: flex; flex-direction: column; gap: 8px; }",
  ".cuckoo-blur-row { display: flex; flex-direction: column; gap: 4px; padding: 10px 12px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 10px; }",
  ".cuckoo-blur-label { font-size: 13px; color: #cfd3ff; display: flex; justify-content: space-between; align-items: center; gap: 6px; }",
  ".cuckoo-delay-label { display: flex; align-items: center; gap: 6px; font-size: 13px; color: #cfd3ff; }",
  ".cuckoo-delay-label .cuckoo-blur-value { white-space: nowrap; flex-shrink: 0; }",
  '.cuckoo-blur-value { font-size: 12px; color: #8b93ff; font-family: "Consolas", monospace; font-weight: 600; }',
  '.cuckoo-input { width: 70px; background: rgba(15,18,32,0.6); border: 1px solid rgba(255,255,255,0.1); border-radius: 8px; padding: 5px 8px; color: #dde1ff; font-size: 12px; font-family: "Consolas", monospace; outline: none; transition: border-color 0.18s; }',
  ".cuckoo-input:focus { border-color: rgba(139,147,255,0.6); }",

  ".cuckoo-label { font-size: 12px; font-weight: 600; color: #c8ccff; text-transform: uppercase; letter-spacing: 0.6px; cursor: pointer; margin-bottom: 2px; }",
  ".cuckoo-cmd-preview {",
  "  background: rgba(15,18,32,0.6); border: 1px solid rgba(255,255,255,0.1);",
  "  border-radius: 10px; padding: 10px 12px;",
  '  font-family: "Cascadia Code", "Fira Code", "Consolas", monospace;',
  "  font-size: 12px; color: #a7f3c0; line-height: 1.5;",
  "  max-height: 140px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;",
  "}",
  ".cuckoo-actions { display: flex; gap: 8px; width: 100%; flex-wrap: wrap; }",
  ".cuckoo-actions .cuckoo-btn { flex: 1 1 auto; min-width: 0; white-space: nowrap; }",
  ".cuckoo-btn {",
  "  flex: 1; padding: 9px 10px; border: 1px solid transparent; border-radius: var(--cuckoo-overlay-btn-radius, 10px);",
  "  font-size: 12.5px; font-weight: 600; cursor: pointer;",
  "  transition: all 0.22s ease; letter-spacing: 0.3px;",
  "  white-space: nowrap; text-overflow: ellipsis; overflow: hidden;",
  "}",
  ".cuckoo-btn:active { transform: scale(0.98); }",
  ".cuckoo-btn-primary {",
  "  background: var(--cuckoo-overlay-primary-bg, linear-gradient(135deg, #8b93ff, #6d76ff)); color: #fff;",
  "  box-shadow: 0 6px 18px var(--cuckoo-overlay-primary-shadow, rgba(109, 118, 255, 0.25));",
  "}",
  ".cuckoo-btn-primary:hover { box-shadow: 0 8px 22px var(--cuckoo-overlay-primary-shadow-hover, rgba(109, 118, 255, 0.4)); transform: translateY(-1px); }",
  ".cuckoo-btn-primary:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }",
  ".cuckoo-btn-secondary {",
  "  background: var(--cuckoo-overlay-secondary-bg, rgba(139,147,255,0.12)); color: var(--cuckoo-overlay-secondary-text, #a8afff);",
  "  border-color: var(--cuckoo-overlay-secondary-border, rgba(139, 147, 255, 0.5));",
  "}",
  ".cuckoo-btn-secondary:hover { background: var(--cuckoo-overlay-secondary-hover-bg, rgba(139, 147, 255, 0.28)); color: #fff; border-color: var(--cuckoo-overlay-secondary-hover-border, rgba(139, 147, 255, 0.75)); transform: translateY(-1px); }",
  ".cuckoo-btn-text {",
  "  background: none; border: none; color: var(--ck-text-dim); padding: 4px 0;",
  "  text-align: left; font-size: 11px; cursor: pointer; transition: color 0.2s;",
  "}",
  ".cuckoo-btn-text:hover { color: var(--ck-red); }",
  ".cuckoo-result-status { font-size: 12px; font-weight: 600; padding: 2px 0; }",
  "#cuckoo-result-section { background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 10px; padding: 10px 12px; }",
  ".cuckoo-result-status.success { color: var(--ck-green); }",
  ".cuckoo-result-status.error { color: var(--ck-red); }",
  ".cuckoo-result-output {",
  "  background: rgba(15,18,32,0.6); border: 1px solid rgba(255,255,255,0.1);",
  "  border-radius: 10px; padding: 10px 12px;",
  '  font-family: "Cascadia Code", "Fira Code", "Consolas", monospace;',
  "  font-size: 11.5px; color: #c8ccff; line-height: 1.5;",
  "  max-height: 200px; overflow: auto; white-space: pre-wrap; word-break: break-all; margin: 0;",
  "}",
  ".cuckoo-history-list { max-height: 140px; overflow-y: auto; display: flex; flex-direction: column; gap: 6px; }",
  ".cuckoo-history-item {",
  "  background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 10px; padding: 8px 10px;",
  "  font-size: 12px; cursor: pointer; transition: background 0.2s, border-color 0.2s;",
  "}",
  ".cuckoo-history-item:hover { background: rgba(139, 147, 255, 0.18); border-color: rgba(139,147,255,0.45); }",
  ".cuckoo-history-item .cuckoo-cmd-text {",
  '  font-family: "Consolas", monospace; color: #a7f3c0; font-size: 12px;',
  "  display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;",
  "}",
  ".cuckoo-history-item .cuckoo-cmd-status { font-size: 11px; margin-top: 2px; display: block; }",
  ".cuckoo-history-item .cuckoo-cmd-status.success { color: var(--ck-green); }",
  ".cuckoo-history-item .cuckoo-cmd-status.error { color: var(--ck-red); }",
  ".cuckoo-history-item .cuckoo-cmd-time { font-size: 10px; color: #5d6280; margin-top: 2px; display: block; }",
  "#cuckoo-mcp-manager { width: 780px; max-width: 90vw; }",
  "#cuckoo-mcp-manager .cuckoo-mcp-body { flex-direction: row; gap: 14px; align-items: stretch; overflow: hidden; }",
  ".cuckoo-mcp-left { width: 220px; flex-shrink: 0; display: flex; flex-direction: column; }",
  ".cuckoo-mcp-left .cuckoo-session-list { flex: 1; max-height: none; overflow-y: auto; }",
  ".cuckoo-mcp-right { flex: 1; display: flex; flex-direction: column; gap: 10px; }",
  ".cuckoo-mcp-json { flex: 1; min-height: 55vh; resize: vertical; }",
  ".cuckoo-mcp-right .cuckoo-btn { flex: 0 0 auto; align-self: flex-start; }",
  ".cuckoo-window-manager {",
  "  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);",
  "  z-index: 2147483647; width: 520px; height: 80vh; max-height: 85vh;",
  "  background: rgba(17, 19, 34, 0.98);",
  "  border: 1px solid var(--ck-border); border-radius: 16px;",
  "  display: flex; flex-direction: column; overflow: hidden;",
  "  box-shadow: 0 16px 50px rgba(0, 0, 0, 0.55), 0 0 0 1px rgba(139, 147, 255, 0.08);",
  "  transition: opacity 0.22s ease, transform 0.22s ease;",
  "}",
  ".cuckoo-window-manager.cuckoo-hidden { opacity: 0; pointer-events: none; transform: translate(-50%, -50%) scale(0.95); }",
  ".cuckoo-wm-header {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  padding: 12px 16px 10px; flex-shrink: 0;",
  "  border-bottom: 1px solid var(--ck-border);",
  "  background: rgba(255, 255, 255, 0.02);",
  "}",
  ".cuckoo-wm-body { padding: 12px 14px; overflow: hidden; flex: 1; display: flex; flex-direction: column; gap: 12px; }",
  ".cuckoo-window-item {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  background: var(--ck-surface); border: 1px solid var(--ck-border);",
  "  border-radius: 10px; padding: 10px 12px; cursor: pointer;",
  "  transition: background 0.2s; font-size: 12px;",
  "  gap: 8px;",
  "}",
  ".cuckoo-window-item:hover { background: rgba(139, 147, 255, 0.18); }",
  ".cuckoo-window-left { display: flex; align-items: center; gap: 6px; flex: 1; min-width: 0; }",
  ".cuckoo-window-item .cuckoo-window-name { color: #c8ccff; font-weight: 600; flex-shrink: 0; }",
  ".cuckoo-window-item .cuckoo-window-sep { color: #5d6280; flex-shrink: 0; }",
  ".cuckoo-window-item .cuckoo-window-status { color: #8a90b8; font-size: 11px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".cuckoo-window-del {",
  "  color: #ff6b7a; cursor: pointer; font-size: 11px; padding: 2px 6px;",
  "  border-radius: 6px; flex-shrink: 0; transition: all 0.2s;",
  "}",
  ".cuckoo-window-del:hover { background: rgba(255, 107, 122, 0.18); color: #fff; }",
  ".cuckoo-window-item.active { border-color: rgba(139, 147, 255, 0.5); background: rgba(139, 147, 255, 0.12); }",
  "#cuckoo-window-list { max-height: none; flex: 1; min-height: 200px; overflow-y: auto; }",
  "#cuckoo-window-list .cuckoo-window-item { flex-shrink: 0; }",
  "#cuckoo-status-badge {",
  "  position: fixed; bottom: 24px; right: 24px; z-index: 2147483647;",
  "  width: 48px; height: 48px; border-radius: 50%;",
  "  background: rgba(139, 147, 255, 0.22); border: 1px solid rgba(139, 147, 255, 0.4);",
  "  will-change: transform;",
  "  display: flex; align-items: center; justify-content: center; gap: 0;",
  "  cursor: pointer;",
  "  transition: background 0.2s, border-color 0.2s, transform 0.15s;",
  "}",
  "#cuckoo-status-badge:hover { background: rgba(139, 147, 255, 0.35); border-color: rgba(139, 147, 255, 0.65); transform: scale(1.05); }",
  "#cuckoo-status-dot {",
  "  position: absolute; top: 6px; right: 6px;",
  "  width: 9px; height: 9px; border-radius: 50%;",
  "  background: var(--ck-green); animation: cuckoo-pulse 2s infinite;",
  "}",
  ".cuckoo-fab-icon {",
  "  display: flex; align-items: center; justify-content: center;",
  "  width: 26px; height: 22px;",
  "  color: #a8afff;",
  "  user-select: none;",
  "}",
  ".cuckoo-fab-icon svg {",
  "  width: 100%; height: 100%;",
  "  display: block;",
  "}",
  ".cuckoo-toast {",
  "  position: fixed; top: 18px; left: 50%; transform: translateX(-50%) translateY(-8px);",
  "  z-index: 2147483648; min-width: 200px; max-width: 380px; text-align: center;",
  "  background: rgba(22, 24, 44, 0.92); backdrop-filter: blur(18px);",
  "  -webkit-backdrop-filter: blur(18px);",
  "  border: 1px solid rgba(139, 147, 255, 0.28); border-radius: 12px;",
  "  padding: 10px 16px; font-size: 13px; color: #dde1ff;",
  "  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.35);",
  "  opacity: 0; pointer-events: none; transition: opacity 0.22s ease, transform 0.22s ease;",
  "}",
  ".cuckoo-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }",
  ".cuckoo-task-status {",
  "  display: inline-flex; align-items: center; gap: 5px;",
  "  color: #a8afff; font-size: 11px; font-weight: 600;",
  "}",
  ".cuckoo-btn-kill {",
  "  margin-left: 6px; padding: 2px 8px;",
  "  border: 1px solid rgba(255, 107, 122, 0.55); border-radius: 7px;",
  "  background: rgba(255, 107, 122, 0.16); color: #ff8a95;",
  "  font-size: 10.5px; font-weight: 700; letter-spacing: 0.3px;",
  "  cursor: pointer; transition: all 0.2s ease; line-height: 1.4;",
  "}",
  ".cuckoo-btn-kill:hover { background: rgba(255, 107, 122, 0.32); color: #fff; border-color: rgba(255, 107, 122, 0.9); }",
  ".cuckoo-btn-kill:active { transform: scale(0.96); }",
  ".cuckoo-btn-kill:disabled { opacity: 0.5; cursor: not-allowed; }",
  ".cuckoo-spinner {",
  "  width: 11px; height: 11px; border-radius: 50%;",
  "  border: 2px solid rgba(139,147,255,0.25); border-top-color: #8b93ff;",
  "  animation: cuckoo-spin 0.8s linear infinite;",
  "}",
  "@keyframes cuckoo-spin { to { transform: rotate(360deg); } }",
  "@keyframes cuckoo-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.35; } }",
  "@keyframes cuckoo-attention {",
  "  0%, 100% { transform: scale(1); }",
  "  10%, 30%, 50%, 70%, 90% { transform: scale(1.08); }",
  "  20%, 40%, 60%, 80% { transform: scale(0.98); }",
  "}",
  ".cuckoo-btn-attention {",
  "  animation: cuckoo-attention 1s ease-in-out 3;",
  "  background: rgba(139, 147, 255, 0.35) !important;",
  "  color: #fff !important;",
  "  border-color: rgba(139, 147, 255, 0.6) !important;",
  "}",
  ".cuckoo-hidden { display: none !important; }",
  ".cuckoo-home-mode .cuckoo-header .cuckoo-btn-icon,",
  ".cuckoo-home-mode .cuckoo-body .cuckoo-section,",
  ".cuckoo-home-mode .cuckoo-body .cuckoo-actions:not(:has(#cuckoo-btn-init)),",
  ".cuckoo-home-mode .cuckoo-divider {",
  "  display: none !important;",
  "}",
  ".cuckoo-overlay ::-webkit-scrollbar { width: 6px; }",
  ".cuckoo-overlay ::-webkit-scrollbar-track { background: transparent; }",
  ".cuckoo-overlay ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.15); border-radius: 3px; }",
  ".cuckoo-overlay ::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.25); }",
  ".cuckoo-project-dir-section {",
  "  background: rgba(255,255,255,0.04); border-radius: 10px;",
  "  padding: 10px 12px; border: 1px solid rgba(255,255,255,0.08);",
  "}",
  ".cuckoo-project-dir-row { display: flex; justify-content: space-between; align-items: center; }",
  ".cuckoo-btn-change-dir {",
  "  background: rgba(139,147,255,0.12); border: 1px solid rgba(139,147,255,0.5);",
  "  color: #a8afff; padding: 3px 10px; border-radius: 8px;",
  "  cursor: pointer; font-size: 11px; font-weight: 600; transition: all 0.18s;",
  "}",
  ".cuckoo-btn-change-dir:hover { background: rgba(139,147,255,0.28); color: #fff; border-color: rgba(139,147,255,0.75); }",
  '.cuckoo-project-dir-display { margin-top: 4px; font-size: 12px; font-family: "Consolas", monospace; color: #8a90b8; word-break: break-all; }',
  ".cuckoo-dir-path { color: #a7f3c0; }",
  ".cuckoo-token-section { background: var(--ck-surface); border-radius: 10px; padding: 8px 10px; border: 1px solid var(--ck-border); }",
  ".cuckoo-token-display { display: flex; align-items: baseline; gap: 6px; margin-top: 2px; }",
  '.cuckoo-token-count { font-size: 20px; font-weight: 700; color: #a7f3c0; font-family: "Consolas", monospace; }',
  ".cuckoo-token-unit { font-size: 11px; color: var(--ck-text-dim); }",
  ".cuckoo-divider { border-top: 1px solid var(--ck-border); margin: 2px 0; }",
  ".cuckoo-session-section {",
  "  background: rgba(255,255,255,0.04); border-radius: 10px;",
  "  padding: 10px 12px; border: 1px solid rgba(255,255,255,0.08);",
  "}",
  ".cuckoo-session-header { display: flex; justify-content: space-between; align-items: center; }",
  ".cuckoo-btn-refresh-sessions {",
  "  background: rgba(139,147,255,0.12); border: 1px solid rgba(139,147,255,0.5);",
  "  color: #a8afff; padding: 3px 10px; border-radius: 8px;",
  "  cursor: pointer; font-size: 11px; font-weight: 600; transition: all 0.18s;",
  "}",
  ".cuckoo-btn-refresh-sessions:hover { background: rgba(139,147,255,0.28); color: #fff; border-color: rgba(139,147,255,0.75); }",
  ".cuckoo-session-list { max-height: 100px; overflow-y: auto; margin-top: 4px; display: flex; flex-direction: column; gap: 4px; }",
  '.cuckoo-session-item { background: rgba(255,255,255,0.05); border-radius: 8px; padding: 6px 10px; font-size: 12px; font-family: "Consolas", monospace; color: #ccc; cursor: pointer; transition: background 0.2s; }',
  ".cuckoo-session-item:hover { background: rgba(139,147,255,0.2); }",
  ".cuckoo-session-item .session-id { color: #a8afff; font-size: 11px; }",
  ".cuckoo-session-item .session-action { color: #a7f3c0; font-size: 11px; font-weight: 600; }",
  ".cuckoo-session-empty { color: #5d6280; font-size: 12px; font-style: italic; padding: 8px 0; text-align: center; }",
  ".cuckoo-first-time-dialog {",
  "  position: fixed; top: 0; left: 0; right: 0; z-index: 2147483647;",
  "  display: flex; align-items: flex-start; justify-content: center;",
  "  padding-top: 24px;",
  "  pointer-events: none;",
  "}",
  ".cuckoo-first-time-dialog.cuckoo-hidden { display: none !important; }",
  ".cuckoo-first-time-dialog.cuckoo-enter {",
  "  animation: cuckoo-first-time-fade-in 0.35s cubic-bezier(0.16, 1, 0.3, 1) both;",
  "}",
  ".cuckoo-first-time-dialog.cuckoo-enter .cuckoo-first-time-box {",
  "  animation: cuckoo-first-time-box-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both;",
  "}",
  ".cuckoo-first-time-dialog.cuckoo-closing {",
  "  animation: cuckoo-first-time-fade-out 0.22s ease-in both;",
  "}",
  ".cuckoo-first-time-box {",
  "  position: relative; max-width: 420px; width: 90%;",
  "  background: rgba(17, 19, 34, 0.98);",
  "  border: 1px solid rgba(139, 147, 255, 0.35);",
  "  border-radius: 18px;",
  "  padding: 28px 24px 22px;",
  "  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(139, 147, 255, 0.08);",
  "  color: var(--ck-text); font-size: 14px; line-height: 1.6;",
  "  text-align: center;",
  "  pointer-events: auto;",
  "}",
  ".cuckoo-first-time-dialog.cuckoo-closing .cuckoo-first-time-box {",
  "  animation: cuckoo-first-time-box-out 0.22s ease-in both;",
  "}",
  "@keyframes cuckoo-first-time-fade-in { from { opacity: 0; } to { opacity: 1; } }",
  "@keyframes cuckoo-first-time-fade-out { from { opacity: 1; } to { opacity: 0; } }",
  "@keyframes cuckoo-first-time-box-in {",
  "  from { opacity: 0; transform: translateY(-14px) scale(0.96); }",
  "  to { opacity: 1; transform: translateY(0) scale(1); }",
  "}",
  "@keyframes cuckoo-first-time-box-out {",
  "  from { opacity: 1; transform: translateY(0) scale(1); }",
  "  to { opacity: 0; transform: translateY(-10px) scale(0.97); }",
  "}",
  ".cuckoo-first-time-close { position: absolute; top: 10px; right: 10px; }",
  ".cuckoo-first-time-text { margin-bottom: 18px; color: #dde1ff; }",
  ".cuckoo-first-time-box .cuckoo-actions { justify-content: center; }",
  ".cuckoo-first-time-box .cuckoo-btn { flex: 0 0 auto; min-width: 150px; }",
  // ========== CSS-переменные (управляются из настроек Cookie Code) ==========
  ":root {",
  "  --cuckoo-bg-blur: 0px;", // размытие самой картинки фона
  "  --cuckoo-header-blur: 12px;", // стекло шапки
  "  --cuckoo-sidebar-blur: 12px;", // стекло сайдбара
  "  --cuckoo-header-opacity: 45%;", // плотность фона шапки (0 = прозрачно)
  "  --cuckoo-sidebar-opacity: 45%;", // плотность фона сайдбара (0 = прозрачно)
  "  --cuckoo-toolblock-opacity: 55%;", // плотность фона tool-блоков
  "  --cuckoo-toolblock-blur: 0px;", // стекло tool-блоков
  "  --cuckoo-input-glass-opacity: 55%;", // плотность фона поля ввода
  "  --cuckoo-input-glass-blur: 12px;", // стекло поля ввода
  "}",
  // ========== 页面背景：базовый цвет + стили (картинка ставится через JS) ==========
  // При выключенной кастомизации (класс cuckoo-customization-off на <html>)
  // правила не применяются, и фон остаётся родным фоном страницы DeepSeek.
  "html:not(.cuckoo-customization-off), body:not(.cuckoo-customization-off) {",
  "  background-color: #0f1220 !important;",
  "  background-size: cover !important;",
  "  background-position: center center !important;",
  "  background-repeat: no-repeat !important;",
  "  background-attachment: fixed !important;",
  "}",
  // ========== Размытие самой фоновой картинки (--cuckoo-bg-blur) ==========
  // Отдельный fixed-слой поверх body, чтобы фильтр не затрагивал контент.
  "html:not(.cuckoo-customization-off)::before {",
  '  content: "";',
  "  position: fixed;",
  "  inset: 0;",
  "  background: inherit;",
  "  background-image: inherit;",
  "  background-size: cover;",
  "  background-position: center center;",
  "  background-attachment: fixed;",
  "  filter: blur(var(--cuckoo-bg-blur));",
  "  transform: scale(1.05);", // скрываем размытые края по периметру
  "  pointer-events: none;",
  "  z-index: -1;",
  "}",
  // ========== 页面顶部标题栏毛玻璃（DeepSeek） ==========
  // Прозрачность управляется переменной --cuckoo-header-opacity (0% — полностью прозрачно).
  ".the-header {",
  "  backdrop-filter: blur(var(--cuckoo-header-blur)) saturate(140%) !important;",
  "  -webkit-backdrop-filter: blur(var(--cuckoo-header-blur)) saturate(140%) !important;",
  "  background: rgba(15, 18, 32, var(--cuckoo-header-opacity)) !important;",
  "}",
  // ========== 去掉输入框底部的深色渐变，让背景图透出 ==========
  // DeepSeek 在 _871cbca 与其空的子层 d72636e2 上画了从上到下的
  // 线性渐变（底部是不透明的 rgb(21,21,23)），会挡住页面背景图。
  // 用简写 background: transparent !important 一次清掉颜色+渐变。
  "._871cbca,",
  "._871cbca > .d72636e2 {",
  "  background: transparent !important;",
  "}",
  // ========== 左侧边栏毛玻璃（DeepSeek） ==========
  // .b8812f16.a2f3d50e — корень сайдбара. Внутри много слоёв, каждый со своим
  // фоном (шапка _262baab, список _3586175/_6d215eb/_77cdc67, низ _7b40dad).
  // Делаем прозрачными все промежуточные слои, чтобы стекло работало насквозь.
  ".b8812f16.a2f3d50e,",
  ".b8812f16.a2f3d50e > div,",
  ".b8812f16.a2f3d50e > div > div,",
  ".b8812f16.a2f3d50e ._262baab,",
  ".b8812f16.a2f3d50e ._3586175,",
  ".b8812f16.a2f3d50e ._6d215eb,",
  ".b8812f16.a2f3d50e ._77cdc67,",
  ".b8812f16.a2f3d50e ._7b40dad,",
  ".b8812f16.a2f3d50e ._8a693f3,",
  ".b8812f16.a2f3d50e ._1d72f01,",
  ".b8812f16.a2f3d50e .f3d18f6a,",
  ".b8812f16.a2f3d50e ._3098d02 {",
  "  background: transparent !important;",
  "  backdrop-filter: none !important;",
  "  -webkit-backdrop-filter: none !important;",
  "}",
  // Стекло применяем один раз — на корень сайдбара.
  // Прозрачность — переменная --cuckoo-sidebar-opacity (0% — полностью прозрачно).
  ".b8812f16.a2f3d50e {",
  "  background: rgba(15, 18, 32, var(--cuckoo-sidebar-opacity)) !important;",
  "  backdrop-filter: blur(var(--cuckoo-sidebar-blur)) saturate(140%) !important;",
  "  -webkit-backdrop-filter: blur(var(--cuckoo-sidebar-blur)) saturate(140%) !important;",
  "}",
  // ========== 隐藏底部「Сгенерировано ИИ」免责声明 ==========
  "._0fcaa63 {",
  "  display: none !important;",
  "}",
  // ========== Ошибка «Слишком частые сообщения» (DeepSeek rate limit) — красный текст ==========
  // Хэш _1ce76f5 нестабилен, поэтому цепляемся к нему + страховка через :has()
  // и любые элементы с этим текстом внутри сообщений.
  "._1ce76f5,",
  '[class*="_1ce76f5"] {',
  "  color: #ff6b7a !important;",
  "  font-weight: 600 !important;",
  "}",
  // Страховка: любой span внутри сообщения, содержащий «Слишком частые сообщения»
  "p:has(> span):has(._1ce76f5),",
  "div:has(> ._1ce76f5) {",
  "  color: #ff6b7a !important;",
  "}",
  // ========== Модалка «Настройки» (и другие ds-modal) — матовое стекло ==========
  ".ds-modal-content {",
  "  background: rgba(15, 18, 32, 0.55) !important;",
  "  backdrop-filter: blur(16px) saturate(140%) !important;",
  "  -webkit-backdrop-filter: blur(16px) saturate(140%) !important;",
  "}",
  // Приглушаем фон-маску, чтобы под модалкой просвечивала страница
  ".ds-modal-mask {",
  "  background: rgba(0, 0, 0, 0.35) !important;",
  "}",
  // ========== Матовое стекло для поля ввода сообщения DeepSeek ==========
  // Приём тот же, что у плашки «Размышление»: backdrop-filter не работает,
  // потому что контейнер инпута лежит внутри виртуализированного списка с
  // transform. Поэтому стекло рисуем сами: ::before показывает тот же фон
  // страницы, размытый и спозиционированный под вьюпорт; ::after добавляет
  // лёгкую затемняющую плёнку. Координаты считает input-glass.js.
  // Селекторы из DOM: внешняя обёртка блока ввода _77cefa5 (у неё непрозрачный
  // фон), внутренний контейнер _020ab5b, textarea[name="search"].
  // Внешняя обёртка блока ввода — именно у неё непрозрачный фон (белый/тёмный)
  // и border-radius 24px. Именно её делаем стеклянной.
  // Дополнительно правило отключается классом cuckoo-input-glass-off на <html>
  // (чекбокс «Стекло поля ввода включено» в настройках).
  "html:not(.cuckoo-customization-off):not(.cuckoo-input-glass-off) ._77cefa5 {",
  "  position: relative !important;",
  "  overflow: hidden !important;",
  "  border-radius: 24px !important;",
  "  border: 1px solid rgba(139, 147, 255, 0.22) !important;",
  "  background: transparent !important;",
  "  backdrop-filter: none !important;",
  "  -webkit-backdrop-filter: none !important;",
  "}",
  // Псевдоэлемент рисует тот же фон страницы, размытый (backdrop-filter не
  // работает: предки внутри виртуализированного списка с transform).
  "html:not(.cuckoo-customization-off):not(.cuckoo-input-glass-off) ._77cefa5::before {",
  '  content: "" !important;',
  "  position: absolute !important;",
  "  inset: calc(-1 * var(--cuckoo-input-pad, 40px)) !important;",
  "  background-image: var(--cuckoo-bg-image, none) !important;",
  "  background-size: var(--cuckoo-input-bg-size, cover) !important;",
  "  background-repeat: no-repeat !important;",
  "  background-position: var(--cuckoo-input-bg-pos, 0 0) !important;",
  "  filter: blur(var(--cuckoo-input-glass-blur, 12px)) !important;",
  "  -webkit-filter: blur(var(--cuckoo-input-glass-blur, 12px)) !important;",
  "  pointer-events: none !important;",
  "  z-index: 0 !important;",
  "}",
  "html:not(.cuckoo-customization-off):not(.cuckoo-input-glass-off) ._77cefa5::after {",
  '  content: "" !important;',
  "  position: absolute !important;",
  "  inset: 0 !important;",
  "  background: rgba(15, 18, 32, var(--cuckoo-input-glass-opacity, 55%)) !important;",
  "  pointer-events: none !important;",
  "  z-index: 0 !important;",
  "}",
  // Внутренний контейнер ввода — прозрачный, контент поверх стекла.
  "html:not(.cuckoo-customization-off):not(.cuckoo-input-glass-off) ._020ab5b {",
  "  position: relative !important;",
  "  background: transparent !important;",
  "  z-index: 1 !important;",
  "}",
  'html:not(.cuckoo-customization-off):not(.cuckoo-input-glass-off) ._020ab5b textarea[name="search"],',
  "html:not(.cuckoo-customization-off):not(.cuckoo-input-glass-off) ._020ab5b ._24fad49 {",
  "  background: transparent !important;",
  "}",
  // ========== Кнопка «Новый чат» в сайдбаре — матовое стекло ==========
  "._5a8ac7a.a084f19e {",
  "  background: rgba(15, 18, 32, 0.5) !important;",
  "  backdrop-filter: blur(10px) saturate(140%) !important;",
  "  -webkit-backdrop-filter: blur(10px) saturate(140%) !important;",
  "  border: 1px solid rgba(139, 147, 255, 0.2) !important;",
  "  border-radius: 12px !important;",
  "}",
  // ========== Рендер tool-блоков (cuckoo) — как в dsh-web-dev ==========
  ".cuckoo-tool-block {",
  "  margin: 8px 0;",
  "  border: 1px solid rgba(139, 147, 255, 0.22);",
  "  border-radius: 10px;",
  "  background: rgba(15, 18, 32, var(--cuckoo-toolblock-opacity)) !important;",
  "  backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;",
  "  -webkit-backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;",
  "  overflow: hidden;",
  "  min-height: 0 !important;",
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
  "}",
  '.cuckoo-tool-block[data-expanded="false"] > .md-code-block {',
  "  display: none !important;",
  "  height: 0 !important;",
  "  min-height: 0 !important;",
  "}",
  ".cuckoo-tool-header {",
  "  display: flex; align-items: center; gap: 8px;",
  "  padding: 8px 12px;",
  "  cursor: pointer;",
  "  user-select: none;",
  "  font-size: 13px;",
  "  color: #dde1ff;",
  "  transition: background 0.15s;",
  "}",
  ".cuckoo-tool-header:hover { background: rgba(139, 147, 255, 0.09); }",
  ".cuckoo-tool-chevron {",
  "  display: inline-block; width: 12px; text-align: center;",
  "  color: #8a90b8; font-size: 11px;",
  "}",
  ".cuckoo-tool-icon {",
  "  display: inline-flex; align-items: center; justify-content: center;",
  "  width: 16px; height: 16px;",
  "  color: #a8afff;",
  "  flex-shrink: 0;",
  "}",
  ".cuckoo-tool-icon svg {",
  "  width: 16px !important; height: 16px !important;",
  "  display: block;",
  "  stroke: currentColor;",
  "}",
  ".cuckoo-tool-label { font-weight: 600; color: #a8afff; }",
  ".cuckoo-tool-sep { color: #5d6280; }",
  ".cuckoo-tool-file {",
  "  color: #a7f3c0;",
  '  font-family: "Consolas", "Cascadia Code", monospace;',
  "  font-size: 12px;",
  "  text-decoration: underline dashed rgba(167, 243, 192, 0.35);",
  "  cursor: pointer;",
  "}",
  '.cuckoo-tool-diff { margin-left: auto; display: inline-flex; align-items: center; gap: 4px; font-family: "Consolas", "Cascadia Code", monospace; font-size: 11px; font-weight: 600; white-space: nowrap; }',
  ".cuckoo-diff-add { color: #4ade80; }",
  ".cuckoo-diff-del { color: #f87171; }",
  '.cuckoo-tool-block[data-expanded="true"] > .md-code-block {',
  "  display: block !important;",
  "  border-top: 1px solid rgba(255, 255, 255, 0.06);",
  "  margin: 0 !important;",
  "  border-radius: 0 !important;",
  "}",
  // ========== Стиль ошибки tool-блока ==========
  ".cuckoo-tool-block.cuckoo-tool-error {",
  "  border-color: rgba(255, 107, 122, 0.65) !important;",
  "  background: rgba(60, 15, 22, 0.7) !important;",
  "}",
  ".cuckoo-tool-block.cuckoo-tool-error .cuckoo-tool-header {",
  "  background: rgba(255, 107, 122, 0.1);",
  "}",
  ".cuckoo-tool-block.cuckoo-tool-error .cuckoo-tool-label {",
  "  color: #ff8e9b !important;",
  "}",
  ".cuckoo-tool-block.cuckoo-tool-error .cuckoo-tool-chevron {",
  "  color: #ff6b7a !important;",
  "}",
  ".cuckoo-tool-error-icon {",
  "  color: #ff6b7a;",
  "  font-size: 14px;",
  "  margin-left: 4px;",
  "}",
  ".cuckoo-tool-error-msg {",
  "  padding: 8px 12px;",
  "  font-size: 12px;",
  "  color: #ff9aa5;",
  "  background: rgba(255, 107, 122, 0.1);",
  "  border-top: 1px solid rgba(255, 107, 122, 0.3);",
  "  white-space: pre-wrap;",
  "  word-break: break-word;",
  '  font-family: "Consolas", monospace;',
  "}",
  // Внутренний код-блок внутри tool-блока: фон/стекло по тем же переменным
  ".cuckoo-tool-block .md-code-block,",
  ".cuckoo-tool-block .md-code-block-banner-wrap,",
  ".cuckoo-tool-block .md-code-block-banner,",
  ".cuckoo-tool-block pre,",
  ".cuckoo-tool-block code {",
  "  background: rgba(15, 18, 32, var(--cuckoo-toolblock-opacity)) !important;",
  "  backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;",
  "  -webkit-backdrop-filter: blur(var(--cuckoo-toolblock-blur)) !important;",
  "}",
  // Сам pre делаем прозрачным поверх фона контейнера — чтобы не дублировать
  ".cuckoo-tool-block pre,",
  ".cuckoo-tool-block code {",
  "  background: transparent !important;",
  "  backdrop-filter: none !important;",
  "  -webkit-backdrop-filter: none !important;",
  "}",
  // ========== Мета-информация под ответом AI (время + токены + затронутые файлы) ==========
  ".cuckoo-response-meta {",
  "  display: flex; flex-wrap: wrap; align-items: center; gap: 6px;",
  "  margin-top: 6px; padding: 3px 8px;",
  "  font-size: 11px;",
  "  color: #8a90b8;",
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
  "  border-radius: 6px;",
  "  user-select: none;",
  "  opacity: 0.85;",
  "}",
  ".cuckoo-response-meta-item {",
  "  display: inline-flex; align-items: center; gap: 4px;",
  "}",
  ".cuckoo-response-meta-item svg { display: block; }",
  ".cuckoo-response-meta-sep { color: #5d6280; }",
  ".cuckoo-response-meta-produced { display: inline-flex; align-items: center; gap: 6px; flex-wrap: wrap; }",
  ".cuckoo-response-meta-produced-label { color: #6b7280; font-size: 11px; font-weight: 400; }",
  ".cuckoo-produced-chip {",
  "  display: inline-flex; align-items: center; gap: 4px;",
  "  padding: 1px 8px 1px 6px;",
  "  background: rgb(44, 44, 46);",
  "  border: 1px solid rgba(255,255,255,0.06);",
  "  border-radius: 999px;",
  "  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;",
  "  font-size: 11px; line-height: 18px;",
  "  color: #c8ccff; cursor: pointer;",
  "  transition: background .12s ease, border-color .12s ease;",
  "  user-select: none;",
  "}",
  ".cuckoo-produced-chip:hover { background: rgba(139,147,255,0.18); border-color: rgba(139,147,255,0.45); }",
  ".cuckoo-produced-chip:focus-visible { outline: 1px solid rgba(139,147,255,0.6); outline-offset: 1px; }",
  ".cuckoo-produced-chip-icon {",
  "  display: inline-flex; align-items: center; justify-content: center;",
  "  width: 14px; height: 14px;",
  "}",
  ".cuckoo-produced-chip-icon svg {",
  "  width: 14px; height: 14px; flex: 0 0 14px;",
  "}",
  '.cuckoo-produced-chip[data-status="error"] { border-color: rgba(255,107,122,0.45); background: rgba(60,15,22,0.65); }',
  '.cuckoo-produced-chip[data-status="error"] .cuckoo-produced-chip-icon { opacity: .7; }',
  '.cuckoo-produced-chip[data-status="denied"] { border-color: rgba(251,191,36,0.45); background: rgba(60,45,15,0.6); }',
  '.cuckoo-produced-chip[data-status="denied"] .cuckoo-produced-chip-icon { opacity: .7; }',
  ".cuckoo-produced-chip-name { white-space: nowrap; }",
  // ========== RGB-переливание ника пользователя ==========
  // Переливание включается, если у <body> нет класса `cuckoo-rgb-off`.
  // Управляется настройкой rgbUsername из settings.json.
  "body:not(.cuckoo-rgb-off) ._9d8da05 {",
  "  background: linear-gradient(90deg, #ff4d4d, #ffa64d, #ffee4d, #4dff88, #4dd2ff, #8a4dff, #ff4dd2, #ff4d4d);",
  "  background-size: 400% 100%;",
  "  -webkit-background-clip: text;",
  "  background-clip: text;",
  "  -webkit-text-fill-color: transparent;",
  "  color: transparent;",
  "  animation: cuckoo-rgb-username 5s linear infinite;",
  "  font-weight: 600;",
  "}",
  "@keyframes cuckoo-rgb-username {",
  "  0% { background-position: 0% 50%; }",
  "  100% { background-position: 400% 50%; }",
  "}",
  // ========== RGB-переливание приветственного текста на стартовой странице ==========
  // Приветствие — <span> без класса, всегда идёт сразу после SVG с классом .ce41ed1b
  // внутри общего контейнера. Цепляемся к этому span через :has().
  "body:not(.cuckoo-rgb-off) :is(._6c7e7df, div:has(> svg.ce41ed1b)) > span {",
  "  background: linear-gradient(90deg, #ff4d4d, #ffa64d, #ffee4d, #4dff88, #4dd2ff, #8a4dff, #ff4dd2, #ff4d4d);",
  "  background-size: 400% 100%;",
  "  -webkit-background-clip: text;",
  "  background-clip: text;",
  "  -webkit-text-fill-color: transparent;",
  "  color: transparent;",
  "  animation: cuckoo-rgb-username 5s linear infinite;",
  "}",
  // ========== RGB-переливание кнопки «Повторить» (retry под ошибкой ответа) ==========
  // Класс ds-button--warning стабильный (не хешированный). Ограничение .ds-message
  // гарантирует, что не затронутся warning-кнопки в других местах (например, в настройках).
  ".ds-message .ds-button--warning .ds-button__background,",
  ".ds-message .ds-button--warning {",
  "  background: linear-gradient(90deg, #ff4d4d, #ffa64d, #ffee4d, #4dff88, #4dd2ff, #8a4dff, #ff4dd2, #ff4d4d) !important;",
  "  background-size: 400% 100% !important;",
  "  animation: cuckoo-rgb-retry 5s linear infinite !important;",
  "}",
  "@keyframes cuckoo-rgb-retry {",
  "  0% { background-position: 0% 50%; }",
  "  100% { background-position: 400% 50%; }",
  "}",
  // ========== Матовое стекло для плашки «Размышление N секунд» (._5ab5d64) ==========
  // backdrop-filter не сработает: между плашкой и body стоят непрозрачные предки,
  // а виртуализированный список DeepSeek использует transform (ломает fixed-attachment).
  // Поэтому стекло рисуем сами: псевдоэлемент показывает тот же фон, что на странице,
  // размытый и спозиционированный под вьюпорт. Координаты считает reasoning-glass.js.
  "._5ab5d64 {",
  "  position: relative !important;",
  "  overflow: hidden !important;",
  "  border-radius: 10px !important;",
  "  border: 1px solid rgba(139, 147, 255, 0.22) !important;",
  "  background: transparent !important;",
  "  isolation: auto !important;",
  "  transform: none !important;",
  "  backdrop-filter: none !important;",
  "  -webkit-backdrop-filter: none !important;",
  "}",
  // Гасим фоны у прямого предка и у потомков плашки: DeepSeek рисует свои
  // тёмные слои (обёртка _245c867._34a54ec, иконки, span), и они просвечивают
  // через полупрозрачную плашку, давая «чёрную» область слева.
  "._245c867._34a54ec,",
  "._74c0879,",
  "._245c867._34a54ec > *,",
  "._5ab5d64 * {",
  "  background: transparent !important;",
  "  backdrop-filter: none !important;",
  "  -webkit-backdrop-filter: none !important;",
  "}",
  "._5ab5d64::before {",
  '  content: "" !important;',
  "  position: absolute !important;",
  "  inset: calc(-1 * var(--cuckoo-plate-pad, 40px)) !important;",
  "  background-image: var(--cuckoo-bg-image, none) !important;",
  "  background-size: var(--cuckoo-plate-bg-size, cover) !important;",
  "  background-repeat: no-repeat !important;",
  "  background-position: var(--cuckoo-plate-bg-pos, 0 0) !important;",
  "  filter: blur(var(--cuckoo-reasoning-blur, 12px)) !important;",
  "  -webkit-filter: blur(var(--cuckoo-reasoning-blur, 12px)) !important;",
  "  pointer-events: none !important;",
  "  z-index: 0 !important;",
  "}",
  "._5ab5d64::after {",
  '  content: "" !important;',
  "  position: absolute !important;",
  "  inset: 0 !important;",
  "  background: rgba(15, 18, 32, var(--cuckoo-reasoning-opacity, 35%)) !important;",
  "  pointer-events: none !important;",
  "  z-index: 0 !important;",
  "}",
  "._5ab5d64 > * {",
  "  position: relative !important;",
  "  z-index: 1 !important;",
  "}",
  // ========== Панель «Изменения» (git) ==========
  "#cuckoo-diff-panel { width: 560px; max-width: 92vw; height: 72vh; }",
  ".cuckoo-diff-body { overflow: hidden; padding: 0 !important; }",
  ".cuckoo-diff-list { flex: 1; overflow-y: auto; padding: 10px 12px; display: flex; flex-direction: column; gap: 4px; }",
  ".cuckoo-diff-file {",
  "  display: flex; align-items: center; gap: 8px; padding: 7px 10px;",
  "  border-radius: 8px; cursor: pointer; transition: background 0.15s;",
  "  font-size: 12px;",
  "}",
  ".cuckoo-diff-file:hover { background: rgba(139,147,255,0.15); }",
  ".cuckoo-diff-file.active { background: rgba(139,147,255,0.22); }",
  ".cuckoo-diff-file-badge {",
  "  width: 18px; text-align: center; font-weight: 700; font-size: 11px;",
  '  flex-shrink: 0; font-family: "Consolas", monospace;',
  "}",
  ".cuckoo-diff-file-badge.modified { color: #ffc107; }",
  ".cuckoo-diff-file-badge.added { color: #4ade80; }",
  ".cuckoo-diff-file-badge.deleted { color: #ff6b7a; }",
  ".cuckoo-diff-file-badge.renamed { color: #8b93ff; }",
  ".cuckoo-diff-file-badge.untracked { color: #86efac; }",
  ".cuckoo-diff-file-badge.changed { color: #8a90b8; }",
  ".cuckoo-diff-file-path {",
  "  flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;",
  '  font-family: "Consolas", monospace; color: #c8ccff; direction: rtl; text-align: left;',
  "}",
  // Вкладки «Изменения» / «История»
  ".cuckoo-diff-tabs {",
  "  display: flex; gap: 4px; padding: 8px 12px 0; flex-shrink: 0;",
  "  border-bottom: 1px solid var(--ck-border);",
  "}",
  ".cuckoo-diff-tab {",
  "  background: none; border: none; color: #8a90b8; font-size: 12px; font-weight: 600;",
  "  padding: 6px 12px; cursor: pointer; border-bottom: 2px solid transparent;",
  "  transition: color 0.15s, border-color 0.15s;",
  "}",
  ".cuckoo-diff-tab:hover { color: #c8ccff; }",
  ".cuckoo-diff-tab.active { color: #a8afff; border-bottom-color: #8b93ff; }",
  ".cuckoo-commit-item {",
  "  display: flex; flex-direction: column; gap: 2px; padding: 8px 10px;",
  "  border-radius: 8px; cursor: pointer; transition: background 0.15s;",
  "}",
  ".cuckoo-commit-item:hover { background: rgba(139,147,255,0.15); }",
  ".cuckoo-commit-subject-line { font-size: 12px; color: #c8ccff; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  '.cuckoo-commit-meta-line { font-size: 10.5px; color: #5d6280; font-family: "Consolas", monospace; }',
  ".cuckoo-commit-meta-line .cuckoo-commit-hash { color: #8b93ff; }",
  ".cuckoo-commit-files { display: flex; flex-direction: column; flex: 1; overflow: hidden; }",
  ".cuckoo-commit-files-header {",
  "  display: flex; align-items: center; gap: 8px; padding: 8px 12px;",
  "  border-bottom: 1px solid var(--ck-border); flex-shrink: 0;",
  "}",
  ".cuckoo-commit-subject { flex: 1; font-size: 12px; color: #c8ccff; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".cuckoo-diff-viewer {",
  "  position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);",
  "  z-index: 2147483647; width: 92vw; max-width: 1100px; height: 84vh;",
  "  background: rgba(17, 19, 34, 0.99);",
  "  border: 1px solid var(--ck-border); border-radius: 16px;",
  "  display: flex; flex-direction: column; overflow: hidden;",
  "  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.65), 0 0 0 1px rgba(139, 147, 255, 0.1);",
  "  transition: opacity 0.18s ease, transform 0.18s ease;",
  "}",
  ".cuckoo-diff-viewer.cuckoo-hidden { opacity: 0; pointer-events: none; transform: translate(-50%, -50%) scale(0.96); }",
  ".cuckoo-diff-viewer-body { flex: 1; overflow: auto; background: rgba(0,0,0,0.25); padding: 8px 0; }",
  ".cuckoo-diff-code {",
  '  font-family: "Cascadia Code", "Consolas", monospace; font-size: 12px; line-height: 1.55;',
  "  margin: 0; padding: 0; white-space: pre;",
  "}",
  ".cuckoo-diff-line { display: flex; }",
  ".cuckoo-diff-line .cuckoo-diff-text { flex: 1; padding: 0 12px; white-space: pre; }",
  ".cuckoo-diff-line.add { background: rgba(74,222,128,0.10); }",
  ".cuckoo-diff-line.add .cuckoo-diff-text { color: #86efac; }",
  ".cuckoo-diff-line.del { background: rgba(255,107,122,0.10); }",
  ".cuckoo-diff-line.del .cuckoo-diff-text { color: #ff9aa5; }",
  ".cuckoo-diff-line.hunk { background: rgba(139,147,255,0.10); }",
  ".cuckoo-diff-line.hunk .cuckoo-diff-text { color: #a8afff; }",
  ".cuckoo-diff-line.meta .cuckoo-diff-text { color: #5d6280; }",
  ".cuckoo-diff-line.ctx .cuckoo-diff-text { color: #8a90b8; }",
  ".cuckoo-diff-empty { padding: 20px; color: #8a90b8; font-size: 13px; text-align: center; }",
  // ========== Окно «Cookie Code» с задачами (слева) ==========
  ".cuckoo-todo-panel {",
  "  position: fixed; top: 90px; left: 20px; z-index: 2147483646;",
  "  width: 380px; max-height: 68vh; display: flex; flex-direction: column;",
  "  background: rgba(17, 19, 34, var(--cuckoo-overlay-bg-opacity, 0.72));",
  "  backdrop-filter: blur(var(--cuckoo-sidebar-blur, 12px)) saturate(140%);",
  "  -webkit-backdrop-filter: blur(var(--cuckoo-sidebar-blur, 12px)) saturate(140%);",
  "  border: 1px solid var(--ck-border); border-radius: 16px;",
  "  box-shadow: 0 12px 40px rgba(0,0,0,0.45), 0 0 0 1px rgba(139,147,255,0.06);",
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
  "  color: var(--ck-text); font-size: 13px; line-height: 1.55; overflow: hidden;",
  "  transition: opacity 0.4s ease, transform 0.4s ease;",
  "}",
  ".cuckoo-todo-panel.cuckoo-hidden { display: flex !important; opacity: 0; pointer-events: none; transform: translateX(-10px); }",
  ".cuckoo-todo-tab {",
  "  position: fixed; top: 90px; left: 0; z-index: 2147483646;",
  "  display: flex; align-items: center; gap: 6px; padding: 8px 9px;",
  "  color: var(--ck-text); background: rgba(17, 19, 34, var(--cuckoo-overlay-bg-opacity, 0.72));",
  "  border: 1px solid var(--ck-border); border-left: 0; border-radius: 0 8px 8px 0;",
  "  box-shadow: 0 8px 26px rgba(0,0,0,0.35); cursor: pointer;",
  '  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif;',
  "  font-size: 12px; font-weight: 700; line-height: 1; transition: opacity 0.2s ease, transform 0.2s ease, background 0.15s ease;",
  "}",
  ".cuckoo-todo-tab:hover { background: rgba(28, 31, 54, 0.9); transform: translateX(2px); }",
  ".cuckoo-todo-tab.cuckoo-hidden { display: none !important; }",
  ".cuckoo-todo-tab-counter { color: var(--ck-text-dim); font-size: 11px; font-weight: 600; }",
  ".cuckoo-todo-header {",
  "  display: flex; align-items: center; justify-content: space-between; gap: 8px;",
  "  padding: 12px 16px 10px; flex-shrink: 0; cursor: grab; user-select: none;",
  "  border-bottom: 1px solid var(--ck-border);",
  "  background: rgba(255,255,255,0.04);",
  "  backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px);",
  "}",
  ".cuckoo-todo-header:active { cursor: grabbing; }",
  ".cuckoo-todo-header-right { display: flex; align-items: center; gap: 8px; }",
  ".cuckoo-todo-title { font-size: 14px; font-weight: 700; color: #c8ccff; letter-spacing: 0.4px; }",
  ".cuckoo-todo-counter { font-size: 11px; color: var(--ck-text-dim); font-weight: 600; }",
  ".cuckoo-todo-body { padding: 10px 12px; overflow-y: auto; flex: 1; }",
  ".cuckoo-todo-list { display: flex; flex-direction: column; gap: 2px; }",
  ".cuckoo-todo-item { display: flex; gap: 7px; align-items: flex-start; padding: 2px 0; }",
  ".cuckoo-todo-icon { flex-shrink: 0; width: 14px; text-align: center; color: #8a90b8; }",
  ".cuckoo-todo-text { flex: 1; word-break: break-word; }",
  ".cuckoo-todo-item.completed .cuckoo-todo-text { color: #8a90b8; text-decoration: line-through; }",
  ".cuckoo-todo-item.completed .cuckoo-todo-icon { color: #4ade80; }",
  ".cuckoo-todo-item.in_progress .cuckoo-todo-text { color: #fff; font-weight: 600; }",
  ".cuckoo-todo-item.in_progress .cuckoo-todo-icon { color: #8b93ff; }",
].join("\n");

module.exports = { buildOverlayHTML, OVERLAY_CSS };
